# Generated by Django 5.2.17 on 2026-09-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_menuitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='menuitem_price_nonnegative'),
        ),
    ]
