# Generated by Django 5.2.17 on 2026-09-23 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_menuitem_menuitem_price_nonnegative'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__lte', Decimal('9999.99'))), name='menuitem_price_maximum'),
        ),
    ]
