# Generated by Django 5.2.17 on 2026-09-23 23:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_menuitem_menuitem_price_maximum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'menuitem'), name='cart_unique_user_menuitem'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='cart_quantity_range'), models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00')), ('unit_price__lte', Decimal('9999.99'))), name='cart_unit_price_range'), models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='cart_price_nonnegative')],
            },
        ),
    ]
